### ISSUE TITLE
When adding a class from the additional attributes parameter, if the class is null, a null reference exception is thrown.

### ISSUE THREAD

**Issue by kevinbourassahoule** [EdCharbeneau/CssBuilder#12]
Probably changing the following line from

https://github.com/EdCharbeneau/CssBuilder/blob/0a491e3e7f2fc680e5b9c7167d2e54de572fcb84/BlazorComponentUtilities/CssBuilder.cs#L120

to 

```C#
 additionalAttributes.TryGetValue("class", out var c) && c != null ? AddClass(c.ToString()) : this; 
```

would do the trick?

**Comment by EdCharbeneau** [comment]
Looks like I need some test coverage to find out. 😄

Thanks for submitting this, I'll take a look.
