### ISSUE TITLE
Make StyleBuilder.AddRaw public

### ISSUE THREAD

**Issue by Jimmys20** [EdCharbeneau/CssBuilder#14]
Hello, `CssBuilder` has the public method `AddValue` that simply appends the string to the buffer without any modification. `StyleBuilder` has a similar method `AddRaw` but it's private. It would be helpful to be able to call this method.

**Comment by richardaubin** [comment]
![image](https://github.com/EdCharbeneau/BlazorComponentUtilities/assets/37956997/d825b770-7daf-401b-a59b-ac9332607690)

AddStyle already does this.

**Comment by Jimmys20** [comment]
@richardaubin, I don't remember why I needed the `AddRaw` method when I opened this issue. Maybe I just used `AddStyle` in the end like you said. Closing the issue.
