### ISSUE TITLE
Create a NuGet package

### ISSUE THREAD

**Issue by EdCharbeneau** [EdCharbeneau/CssBuilder#4]
I'm of the opinion that there's not enough going on here to warrant a NuGet package. However, I've had some requests, if there's enough interest I would reconsider. Please leave a message or up vote if you think a NuGet package would be helpful.

**Comment by dgw2jr** [comment]
Kind of a chicken and egg thing going on here. On one hand there is not enough usage of Razor Components yet to get much interest in something like this. On the other hand you can drive faster adoption of the technology by supporting it (providing a NuGet package for this handy library, for example). 

If I'm trying to sell my team on Blazor/Razor Components it really helps to have the community support like we are already seeing from you and the folks at Telerik.

**Comment by EdCharbeneau** [comment]
Thanks @dgw2jr I'm considering making this a topic for the show (twitch.tv/edcharbeneau) where I show others how to make a NuGet package and publish to NuGet.org

**Comment by EdCharbeneau** [comment]
The NuGet package is now available on NuGet.org 

#Blazor #StateHasChanged
