### ISSUE TITLE
Sign Assembly

### ISSUE THREAD

**Issue by emmanuelbenitez** [EdCharbeneau/CssBuilder#9]
When the assembly is referenced, the compilation returns the following warning:
`CSC : warning CS8002: Referenced assembly 'BlazorComponentUtilities, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

Could you please sign your assembly?

**Comment by EdCharbeneau** [comment]
Will check when .NET 5 compatibility is tested.

**Comment by emmanuelbenitez** [comment]
Hi,

I am updating all my project to .Net 5.0. Do you plan to update to .Net 5.0 and sign your assembly?

**Comment by EdCharbeneau** [comment]
Appreciate the feedback, and sorry for the late response.

I'm still looking for a reason to justify this action. My research both online and through my professional network has advocated against signing the assembly.

See: https://stackoverflow.com/questions/1197133/anything-wrong-with-not-signing-a-net-assembly

Most importantly:

> Signing one assembly has a domino effect on other assemblies

If this is a blocker, you're more than welcome to for the project and recompile your own signed copy for your organization.
